/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: (typeof import('./../src/components/common/AppProvider.vue'))['default']
    NAvatar: (typeof import('naive-ui'))['NAvatar']
    NBreadcrumb: (typeof import('naive-ui'))['NBreadcrumb']
    NBreadcrumbItem: (typeof import('naive-ui'))['NBreadcrumbItem']
    NButton: (typeof import('naive-ui'))['NButton']
    NDropdown: (typeof import('naive-ui'))['NDropdown']
    NImage: (typeof import('naive-ui'))['NImage']
    NLayout: (typeof import('naive-ui'))['NLayout']
    NLayoutContent: (typeof import('naive-ui'))['NLayoutContent']
    NLayoutHeader: (typeof import('naive-ui'))['NLayoutHeader']
    NLayoutSider: (typeof import('naive-ui'))['NLayoutSider']
    NMenu: (typeof import('naive-ui'))['NMenu']
    NScrollbar: (typeof import('naive-ui'))['NScrollbar']
    PageBlock: (typeof import('./../src/components/block/PageBlock.vue'))['default']
    PageHeader: (typeof import('./../src/components/header/PageHeader.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
